# Generated by Django 4.2 on 2023-08-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="description",
            new_name="bio",
        ),
    ]
