# Generated by Django 4.2 on 2023-08-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
