# Generated by Django 4.2 on 2023-08-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="post",
            name="Category",
            field=models.CharField(default="Tech", max_length=50),
        ),
    ]
