# Generated by Django 4.2 on 2023-08-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_category_options_post_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="Category",
            new_name="category",
        ),
    ]
