# Generated by Django 4.2 on 2023-09-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="header_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog\\static\x08log\\images"
            ),
        ),
    ]
