# Generated by Django 4.2 on 2023-10-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="resized_header_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="post_pics_resized"
            ),
        ),
    ]
