# Generated by Django 4.2 on 2023-10-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_alter_post_cropped_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="cropped_image",
        ),
    ]
