# Generated by Django 4.2 on 2023-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="header_image",
            field=models.ImageField(
                blank=True,
                default="default_header_image.png",
                null=True,
                upload_to="post_pics",
            ),
        ),
    ]
